"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MoonIcon, SunIcon } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [darkMode, setDarkMode] = useState(false);
  const [modalShow, setModalShow] = useState(true);
  useEffect(() => {
    if (localStorage.theme === "dark") {
      setDarkMode(true);
    } else {
      setDarkMode(false);
    }
  }, []);

  const handleDarkMode = useCallback(() => {
    setDarkMode((prev) => {
      localStorage.theme = !prev ? "dark" : "light";
      return !prev;
    });
  }, []);

  const closeModal = useCallback(() => {
    setModalShow(false);
  }, [setModalShow]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={`App ${
            darkMode && "dark"
          } bg-gray-200 dark:bg-black/90 min-h-svh flex flex-col`}
        >
          <button
            className="icon-button z-20 fixed right-6 top-1/4 bg-purple-500 text-gray-200  hover:bg-purple-700 dark:hover:text-gray-200 opacity-50 hover:opacity-100"
            onClick={handleDarkMode}
          >
            {!darkMode && <MoonIcon />}
            {darkMode && <SunIcon />}
          </button>

          <Header />

          {children}
        </div>
      </body>
    </html>
  );
}
